git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never
gui: 
  theme:
    activeBorderColor:
      - cyan
      - bold
    inactiveBorderColor:
      - white
    searchingActiveBorderColor:
      - yellow
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - blue
    inactiveViewSelectedLineBgColor:
      - black
    cherryPickedCommitFgColor:
      - cyan
    cherryPickedCommitBgColor:
      - black
    markedBaseCommitFgColor:
      - blue
    markedBaseCommitBgColor:
      - yellow
    unstagedChangesColor:
      - red
    defaultFgColor:
      - white
  authorColors:
    '*': cyan
