#!/usr/bin/env bash
# Omarchy Firefox theme hook — syncs userChrome.css / userContent.css with the
# active Omarchy theme. Auto-generated by this hook; runs on every theme-set.

set -euo pipefail

# Resolve the Firefox profile root (parent of profiles.ini). Covers the legacy
# ~/.mozilla/firefox and the modern ~/.config/mozilla/firefox layouts, in that
# order, plus an explicit MOZ_USER_HOME/MOZ_HOME override when set.
find_profile_root() {
    local root

    if [[ -n "${MOZ_USER_HOME:-}" && -f "$MOZ_USER_HOME/profiles.ini" ]]; then
        echo "$MOZ_USER_HOME"
        return
    fi
    if [[ -n "${MOZ_HOME:-}" && -f "$MOZ_HOME/profiles.ini" ]]; then
        echo "$MOZ_HOME"
        return
    fi
    if [[ -f "$HOME/.mozilla/firefox/profiles.ini" ]]; then
        echo "$HOME/.mozilla/firefox"
        return
    fi
    if [[ -f "$HOME/.config/mozilla/firefox/profiles.ini" ]]; then
        echo "$HOME/.config/mozilla/firefox"
        return
    fi
}

find_default_profile() {
    local root="$1"
    [[ -f "$root/profiles.ini" ]] || return 1

    # Modern Firefox: the active install's Default= dir (matches installs.ini).
    local profile
    profile=$(awk -F= '
        /^\[Install/ { in_install=1 }
        in_install && /^Default=/ { print $2; exit }
    ' "$root/profiles.ini" 2>/dev/null)

    if [[ -n "$profile" ]]; then
        echo "$profile"
        return
    fi

    # Fallback: [Profile*] sections with Default=1.
    awk -F= '
        /^\[Profile/ { in_profile=1; path=""; is_default=0 }
        in_profile && /^Path=/ { path=$2 }
        in_profile && /^Default=1/ { is_default=1 }
        in_profile && /^\[/ { if (is_default && path) { print path; exit } in_profile=0 }
        END { if (is_default && path) print path }
    ' "$root/profiles.ini" 2>/dev/null
}

# --- 1. Locate Firefox ---

if ! command -v firefox >/dev/null 2>&1; then
    echo "firefox: not installed, skipping."
    exit 0
fi

profile_root=$(find_profile_root || true)
if [[ -z "$profile_root" ]]; then
    echo "firefox: no profile root (profiles.ini) found, skipping."
    exit 0
fi

profile_path=$(find_default_profile "$profile_root" || true)
if [[ -z "$profile_path" ]]; then
    echo "firefox: no default profile found, skipping."
    exit 0
fi

profile_dir="$profile_root/$profile_path"
if [[ ! -d "$profile_dir" ]]; then
    echo "firefox: profile dir not found: $profile_dir, skipping."
    exit 0
fi

chrome_dir="$profile_dir/chrome"
mkdir -p "$chrome_dir"

# --- 2. Read resolved theme colors ---

colors_file="$HOME/.local/state/omarchy/current/theme/colors.toml"
if [[ ! -f "$colors_file" ]]; then
    echo "firefox: theme colors.toml not found, skipping."
    exit 0
fi

declare -A C
while IFS=$'\t' read -r key value; do
    C[$key]="${value#\#}"
done < <(omarchy-theme-color --all 2>/dev/null)

# --- 3. Enable legacy userChrome support ---
#
# Use user.js (read & enforced by Firefox at startup, never rewritten by it)
# rather than editing prefs.js, which Firefox rewrites on shutdown and would
# silently discard an appended line.

userjs_file="$profile_dir/user.js"
pref_name="toolkit.legacyUserProfileCustomizations.stylesheets"
pref_line="user_pref(\"$pref_name\", true);"

if [[ -f "$userjs_file" ]]; then
    if grep -q "user_pref(\"$pref_name\", false)" "$userjs_file" 2>/dev/null; then
        sed -i "s/user_pref(\"$pref_name\", false);*/$pref_line/" "$userjs_file"
    elif ! grep -qF "$pref_line" "$userjs_file" 2>/dev/null; then
        echo "$pref_line" >> "$userjs_file"
    fi
else
    echo "$pref_line" > "$userjs_file"
fi

# --- 4. Generate userContent.css (web content) ---

cat > "$chrome_dir/userContent.css" << CSS
/* Omarchy Firefox content theme — auto-generated, do not edit. */

::selection {
    background: #${C[selection]} !important;
    color: #${C[foreground]} !important;
}

* {
    scrollbar-color: #${C[lighter_background]} #${C[muted]} !important;
    scrollbar-width: thin !important;
}

::highlight(search-text) {
    background-color: #${C[accent]} !important;
    color: #${C[background]} !important;
}

:focus-visible {
    outline: 2px solid #${C[accent]} !important;
    outline-offset: 2px !important;
}
CSS

# --- 5. Generate userChrome.css (browser UI) ---

cat > "$chrome_dir/userChrome.css" << CSS
/* Omarchy Firefox chrome theme — auto-generated, do not edit. */

:root {
    color-scheme: ${C[mode]:-dark} !important;
    --toolbar-bgcolor: #${C[background]} !important;
    --toolbar-color: #${C[foreground]} !important;
    --toolbar-text-color: #${C[foreground]} !important;
    --toolbar-field-background-color: #${C[darker_background]} !important;
    --toolbar-field-color: #${C[foreground]} !important;
    --toolbar-field-focus-background-color: #${C[lighter_background]} !important;
    --toolbar-field-focus-color: #${C[foreground]} !important;
    --toolbar-field-border-color: #${C[muted]} !important;
    --toolbox-background-color: #${C[background]} !important;
    --toolbox-background-color-inactive: #${C[background]} !important;
    --toolbox-text-color: #${C[foreground]} !important;
    --tabpanel-background-color: #${C[background]} !important;
    --toolbarbutton-icon-fill: #${C[foreground]} !important;
    --toolbarbutton-background-color-hover: #${C[lighter_background]} !important;
    --toolbarbutton-background-color-active: #${C[darker_background]} !important;
    --toolbarbutton-border-radius: 6px !important;
    --tabs-border-color: #${C[background]} !important;
    --tab-block-margin: 2px !important;
    --sidebar-background-color: #${C[background]} !important;
    --sidebar-text-color: #${C[foreground]} !important;
    --lwt-sidebar-background-color: #${C[background]} !important;
    --lwt-sidebar-text-color: #${C[foreground]} !important;
    --lwt-text-color: #${C[foreground]} !important;
    --arrowpanel-background: #${C[lighter_background]} !important;
    --arrowpanel-color: #${C[foreground]} !important;
    --arrowpanel-border-color: #${C[muted]} !important;
    --panel-separator-zap-gradient: linear-gradient(
        90deg,
        #${C[magenta]} 0%,
        #${C[red]} 52%,
        #${C[yellow]} 100%
    ) !important;
    --focus-outline-color: #${C[accent]} !important;
    --color-accent-primary: #${C[accent]} !important;
    --color-accent-primary-hover: #${C[accent]} !important;
    --color-accent-primary-active: #${C[accent]} !important;
    --in-content-page-background: #${C[background]} !important;
    --in-content-text-color: #${C[foreground]} !important;
    --in-content-link-color: #${C[accent]} !important;
}

#navigator-toolbox {
    background-color: #${C[background]} !important;
    border: none !important;
}

.tab-background[selected="true"] {
    background-color: #${C[lighter_background]} !important;
    background-image: none !important;
    border-radius: 6px !important;
}

.tab-background {
    border-radius: 6px !important;
    border: 0px solid transparent !important;
}

#urlbar-input-container {
    background-color: #${C[darker_background]} !important;
    border-radius: 6px !important;
    border: 0px solid transparent !important;
}

#urlbar[focused="true"] > #urlbar-background {
    box-shadow: none !important;
}

.urlbar-input {
    color: #${C[foreground]} !important;
}

.urlbar-input::placeholder {
    color: #${C[dark_foreground]} !important;
    opacity: 1 !important;
}

#sidebar-box,
#sidebar-box > * {
    background-color: #${C[background]} !important;
    color: #${C[foreground]} !important;
}

#PopupSearchAutoComplete,
#PopupAutoComplete {
    --panel-background: #${C[lighter_background]} !important;
    --panel-color: #${C[foreground]} !important;
    --panel-border-color: #${C[muted]} !important;
}

#identity-box,
#trust-icon-container,
#tracking-protection-icon-container {
    fill: #${C[foreground]} !important;
}

#star-button {
    --toolbarbutton-icon-fill-attention: #${C[accent]} !important;
}

#vertical-tabs,
#sidebar-main {
    background-color: #${C[background]} !important;
    color: #${C[foreground]} !important;
}

#vertical-tabs .tab-label,
#vertical-tabs .tab-icon-image,
sidebar-tab-row,
.tabbrowser-tab .tab-label {
    color: #${C[foreground]} !important;
}

#vertical-tabs .tab-background[selected="true"] {
    background-color: #${C[lighter_background]} !important;
}
CSS

echo "firefox: theme updated."
